language: php

os: linux
dist: xenial

addons:
  apt:
    packages:
      - bc

cache:
  directories:
      - $HOME/cachedir

services:
  - mysql

php:
    - 7.3

env:
    - TEST_SUITE="0-*"
    - TEST_SUITE="1-*"
    - TEST_SUITE="2-*"
    - TEST_SUITE="3-*"

before_install:
  - sudo apt update && sudo apt install libgnutls-openssl27 libgnutls30

install:
  - git clone --depth 1 https://github.com/bats-core/bats-core.git $HOME/bats-core
  - nvm install 8.9
  - nvm use 8.9
  - travis_retry composer install
  - npm install
  - echo -e "[server]\ninnodb_flush_log_at_trx_commit=0" | sudo tee -a /etc/mysql/my.cnf # General speed bump.
  # Move MySQL data to tmpfs (see core travis). Without that we get random timeouts here and there.
  - sudo mkdir /mnt/ramdisk
  - sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
  - sudo service mysql stop
  - sudo mv /var/lib/mysql /mnt/ramdisk
  - sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
  - sudo service mysql restart

before_script:
  - 'git config --global user.email "travis@localhost"'
  - 'git config --global user.name "Travis CI"'
  - 'git config --global core.abbrev 10'
  - "export LOCAL_CI_TESTS_CACHEDIR=$HOME/cachedir && mkdir -p $LOCAL_CI_TESTS_CACHEDIR"
  - "export LOCAL_CI_TESTS_GITDIR=$HOME/gitdir && git clone https://github.com/moodle/moodle $LOCAL_CI_TESTS_GITDIR"
  - "git clone -q --depth 1 https://github.com/moodlehq/moodle-local_codechecker $HOME/moodle-local_codechecker"
  - "export LOCAL_CI_TESTS_PHPCS_DIR=$HOME/moodle-local_codechecker/moodle/"
  - "export LOCAL_CI_TESTS_DBLIBRARY=native"
  - "export LOCAL_CI_TESTS_DBTYPE=mysqli"
  - "export LOCAL_CI_TESTS_DBHOST=localhost"
  - "export LOCAL_CI_TESTS_DBUSER=travis"
  - "export LOCAL_CI_TESTS_DBPASS="
  - "unset _JAVA_OPTIONS" # stderr output on each java execution breaks our json expectations. See travis-ci/travis-ci#8408

script:
  - $HOME/bats-core/bin/bats --timing tests/$TEST_SUITE
